#!/bin/bash

# Navigate to the directory where the scripts are located
cd /home/dadn/Desktop/meditation_gui/video_capture

# Run visual1capture.py in the background
python3 visual_test.py &

# Run visual2capture.py in the background
python3 visual_test2.py &

# Run thermalcapture bash script in the background
./thermalcapture &

sudo python3 Radar_Acquire_NT.py &

# Wait for all background processes to finish
wait


