#!/bin/bash

# Navigate to the directory where the video is located
cd /home/dadn/Desktop/meditation_gui/video_capture


# Define the width and height
width=480
height=640

# Launch the first video
#mpv --geometry=${width}x${height}+0+0 seek.avi 
python3 morphing.py & 

# Launch the second video
sleep 5 && mpv --geometry=${width}x${height}+${width}+0 output_morphed_video.mp4
